CREATE TABLE blog (
  id SERIAL PRIMARY KEY,
  author INTEGER
    REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  html jsonb NOT NULL,
  readers integer[] NOT NULL
);